# Generated by Django 4.2.1 on 2023-05-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='created_at',
        ),
        migrations.AddField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('su', 'Sunny'), ('cl', 'Cloudy'), ('wi', 'Windy'), ('ra', 'Rainy'), ('st', 'Stormy')], default='su', max_length=2),
        ),
    ]
