# Generated by Django 4.2 on 2023-05-01 02:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.URLField(blank=True, default=None)),
            ],
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('has_been_done', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(default=datetime.date(2023, 5, 1))),
                ('date_completion', models.DateTimeField(default=None)),
                ('date_deadline', models.DateTimeField(default=None)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='todo.category')),
            ],
        ),
    ]
