# Generated by Django 4.2 on 2023-05-01 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date_completion',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='todo',
            name='date_deadline',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
