# Generated by Django 4.2 on 2023-05-01 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_date_completion_alter_todo_date_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='date_completion',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='date_deadline',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
