# Generated by Django 4.2 on 2023-04-30 09:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('release_date', models.DateTimeField(default=datetime.date(2023, 4, 30))),
                ('available_in_countries', models.ManyToManyField(blank=True, related_name='countries', to='films.country')),
                ('category', models.ManyToManyField(blank=True, related_name='categories', to='films.category')),
                ('created_in_country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='films.country')),
                ('director', models.ManyToManyField(blank=True, related_name='directors', to='films.director')),
            ],
        ),
    ]
