# Generated by Django 4.2 on 2023-04-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifs', '0002_alter_category_name_alter_gif_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='gifs',
            field=models.ManyToManyField(related_name='categories', to='gifs.gif'),
        ),
    ]
